- name: Ensure monitoring volume directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ docker_path }}/loki'
    - '{{ docker_path }}/promtail'

- name: Copy monitoring template files
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - src: loki.yaml
      dest: '{{ docker_path }}/loki/local-config.yaml'
    - src: promtail.yaml
      dest: '{{ docker_path }}/promtail/config.yml'

- name: Install Grafana Loki logging driver for docker
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver
    state: present
    alias: loki

- name: Deploy docker monitoring
  docker_compose:
    project_name: monitoring
    remove_orphans: true
    definition:
      version: '3'
      services:
        loki:
          image: grafana/loki:latest
          container_name: monitoring_homepage
          restart: unless-stopped
          healthcheck:
            disable: '{{ disable_healthcheck }}'
          logging:
            driver: none
          volumes:
            - '{{ docker_path }}/loki:/etc/loki'
          expose:
            - 3100
          networks:
            - default
          command: -config.file=/etc/loki/local-config.yaml
          labels:
            traefik.http.routers.loki.entrypoints: websecure
            traefik.http.routers.loki.rule: Host(`{{ monitoring_hosts.loki }}`)

        promtail:
          image: grafana/promtail:latest
          container_name: monitoring_promtail
          restart: unless-stopped
          healthcheck:
            disable: '{{ disable_healthcheck }}'
          logging:
            driver: none
          volumes:
            - '{{ docker_path }}/promtail:/etc/promtail'
            - /var/log:/var/log
          networks:
            - default
          command: -config.file=/etc/promtail/config.yml

      networks:
        infrastructure_default:
          external: true
