- name: Deploy docker services
  docker_compose:
    project_name: services
    remove_orphans: true
    definition:
      version: '3'
      services:
        jellyfin:
          image: jellyfin/jellyfin:latest
          container_name: service_jellyfin
          restart: unless-stopped
          healthcheck:
            disable: true
          logging:
            driver: none
          volumes:
            - '{{ docker_path }}/jellyfin/config:/config'
            - '{{ docker_path }}/jellyfin/cache:/cache'
            - '{{ media_path }}:/media'
          ports:
            - 7359:7359/udp
            - 1900:1900/udp
          environment:
            PUID: 1000
            PGID: 1000
            TZ: '{{ timezone }}'
          networks:
            - infrastructure_default
          labels:
            # General configuration
            traefik.enable: true
            # Http configuration
            traefik.http.routers.jellyfin-http.entrypoints: web
            traefik.http.routers.jellyfin-http.rule: Host(`{{ jellyfin_host }}`)
            traefik.http.routers.jellyfin-http.service: jellyfin-http-service
            traefik.http.services.jellyfin-http-service.loadbalancer.server.port: 8096
            # Https configuration
            traefik.http.routers.jellyfin.entrypoints: websecure
            traefik.http.routers.jellyfin.rule: Host(`{{ jellyfin_host }}`)
            traefik.http.routers.jellyfin.service: jellyfin-https-service
            traefik.http.services.jellyfin-https-service.loadbalancer.server.port: 8096
            traefik.http.routers.jellyfin.tls: true

        audiobookshelf:
          image: ghcr.io/advplyr/audiobookshelf:latest
          container_name: service_audiobookshelf
          restart: unless-stopped
          healthcheck:
            disable: true
          logging:
            driver: none
          networks:
            - infrastructure_default
          volumes:
            - '{{ media_path }}/audiobooks:/audiobooks'
            - '{{ media_path }}/podcasts:/podcasts'
            - '{{ docker_path }}/audiobookshelf/config:/config'
            - '{{ docker_path }}/audiobookshelf/metadata:/metadata'
          labels:
            # General configuration
            traefik.enable: true
            # Http configuration
            traefik.http.routers.audiobookshelf-http.entrypoints: web
            traefik.http.routers.audiobookshelf-http.rule: Host(`{{ audiobookshelf_host }}`)
            traefik.http.routers.audiobookshelf-http.middlewares: audiobookshelf-https
            traefik.http.middlewares.audiobookshelf-https.redirectscheme.scheme: https
            # Https configuration
            traefik.http.routers.audiobookshelf.entrypoints: websecure
            traefik.http.routers.audiobookshelf.rule: Host(`{{ audiobookshelf_host }}`)
            traefik.http.routers.audiobookshelf.tls: true

        # dash:
        #   image: mauricenino/dashdot:latest
        #   container_name: service_dash
        #   restart: unless-stopped
        #   privileged: true
        #   healthcheck:
        #     disable: true
        #   logging:
        #     driver: none
        #   networks:
        #     - infrastructure_default
        #   volumes:
        #     - '{{ docker_path }}/dash:/mnt/host:ro'
        #   labels:
        #     # General configuration
        #     traefik.enable: true
        #     # Http configuration
        #     traefik.http.routers.dash-http.entrypoints: web
        #     traefik.http.routers.dash-http.rule: Host(`{{ dash_host }}`)
        #     traefik.http.routers.dash-http.middlewares: dash-https
        #     traefik.http.middlewares.dash-https.redirectscheme.scheme: https
        #     # Https configuration
        #     traefik.http.routers.dash.entrypoints: websecure
        #     traefik.http.routers.dash.rule: Host(`{{ dash_host }}`)
        #     traefik.http.routers.dash.tls: true

      networks:
        infrastructure_default:
          external: true
