version: '3'

tasks:
  default:
    cmds:
      - task --list

  test:
    desc: Tests the connection to the nas
    dir: ansible
    cmds:
      - ansible all -m ping

  setup:
    desc: Setups and configure the NAS
    dir: ansible
    cmds:
      - ansible-playbook setup.yml

  deploy:
    desc: Runs ansible to (re)deploy the services
    dir: ansible
    cmds:
      - ansible-playbook deploy.yml

  test-deploy:
    desc: Tests the docker deployment
    cmds:
      - docker-compose down --rmi all
      - docker compose up -d
