MAKEMKV_ATTRIBUTE_ENUMS = {
    0: "unknown",
    1: "type",
    2: "name",
    3: "lang_code",
    8: "chapter_count",
    9: "duration",
    10: "disk_size",
    11: "disk_size_bytes",
    12: "stream_type_extension",
    13: "bitrate",
    14: "audio_channels_count",
    15: "angle_info",
    17: "audio_sample_rate",
    18: "audio_sample_size",
    19: "video_size",
    20: "video_aspect_ratio",
    21: "video_frame_rate",
    23: "date_time",
    24: "original_title_dd",
    27: "output_file_name",
    28: "metadata_language_code",
    29: "metadata_language_name",
}
