#!/usr/bin/env ansible-playbook

- hosts: all
  become: true

  roles:
    - role: infrastructure
      tags:
        - infrastructure

    #- role: monitoring
    #  tags:
    #    - monitoring

    #- role: media
    #  tags:
    #    - media

    #- role: downloads
    #  tags:
    #    - downloads

    #- role: media_tools
    #  tags:
    #    - media_tools
