- name: Deploy docker infrastructure
  docker_compose:
    project_name: infrastructure
    remove_orphans: true
    definition:
      version: '3'
      services:
        watchtower:
          image: containrrr/watchtower:latest
          container_name: infrastructure_watchtower
          restart: unless-stopped
          healthcheck:
            disable: true
          logging:
            driver: none
          environment:
            WATCHTOWER_SCHEDULE: '0 0 * * * *'
            WATCHTOWER_CLEANUP: 'true'
            TZ: '{{ timezone }}'
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          networks:
            - default

        traefik:
          image: traefik:latest
          container_name: infrastructure_traefik
          restart: unless-stopped
          healthcheck:
            disable: true
          logging:
            driver: none
          ports:
            - 80:80/tcp
            - 443:443/tcp
          volumes:
            - '{{ docker_path }}/traefik:/etc/traefik'
            - '{{ docker_path }}/traefik/certificates:/certs'
            - /var/run/docker.sock:/var/run/docker.sock:ro
          networks:
            - default
          labels:
            # General configuration
            traefik.enable: true
            # Http configuration
            traefik.http.routers.traefik-http.entrypoints: web
            traefik.http.routers.traefik-http.rule: Host(`{{ traefik_host }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            traefik.http.routers.traefik-http.middlewares: traefik-https
            traefik.http.middlewares.traefik-https.redirectscheme.scheme: https
            # Https configuration
            traefik.http.routers.traefik.entrypoints: websecure
            traefik.http.routers.traefik.rule: Host(`{{ traefik_host }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            traefik.http.routers.traefik.service: api@internal
            traefik.http.routers.traefik.tls: true

      networks:
        default:
          driver: bridge
