[tool.poetry]
name = "autorip"
version = "0.1.0"
description = ""
authors = ["DevTobias <tobi.kaerst@gmx.de>"]

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
