- name: Create volume directories if not exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ docker_path }}/dash'
    - '{{ docker_path }}/audiobookshelf/metadata'
    - '{{ docker_path }}/audiobookshelf/config'
    - '{{ docker_path }}/bitwarden'
    - '{{ docker_path }}/sabnzbd/incomplete'
    - '{{ docker_path }}/sabnzbd/downloads'
    - '{{ docker_path }}/sabnzbd/config'
    - '{{ docker_path }}/prowlarr'
    - '{{ docker_path }}/traefik'
    - '{{ docker_path }}/traefik/certificates'
    - '{{ docker_path }}/wireguard'
    - '{{ docker_path }}/jellyseerr/config'
    - '{{ docker_path }}/sonarr/config'
    - '{{ docker_path }}/radarr/config'
    - '{{ docker_path }}/homarr/configs'
    - '{{ docker_path }}/homarr/icons'
    - '{{ docker_path }}/homarr/data'
    - '{{ docker_path }}/jellyfin/config'
    - '{{ docker_path }}/jellyfin/cache'
    - '{{ docker_path }}/kavita/data'

# Traefik configuration

- name: Copy traefik.yaml file
  template:
    src: traefik.yml.j2
    dest: '{{ docker_path }}/traefik/traefik.yml'

- name: Copy certificate
  ansible.builtin.copy:
    src: ../files/certificates/
    dest: '{{ docker_path }}/traefik/certificates/'
